version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=ci_root_pw
      - MYSQL_HOST=course_inventory_mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=course_inventory_local
      - MYSQL_USER=ci_user
      - MYSQL_PASSWORD=ci_pw
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    ports:
      - "4444:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql:delegated
    container_name: course_inventory_mysql
  job:
    build:
        context: .
        dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      - HOW_STARTED=DOCKER_COMPOSE
    volumes:
      - ${HOME}/secrets/course-inventory:/app/config/secrets
      - ${HOME}/data/course-inventory:/app/data
    container_name: course_inventory
